# Generated by Django 2.0.13 on 2019-03-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='picture',
        ),
    ]
